services:
  postgres:
    image: postgres:16-alpine
    container_name: lms_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lms_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: lms_main_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: lms_db
      DB_SSLMODE: disable
    ports:
      - "8080:8080"

volumes:
  postgres_data: